openapi: 3.0.3
info:
  title: Orders API
  version: 1.0.0
paths:
  /orders:
    get:
      summary: List orders
      parameters:
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: size
          schema: { type: integer, default: 10 }
        - in: query
          name: q
          schema: { type: string }
      responses:
        '200':
          description: OK
    post:
      summary: Create order
      parameters:
        - in: header
          name: Idempotency-Key
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [item, price]
              properties:
                item: { type: string }
                price: { type: number }
                status: { type: string, enum: [NEW, PAID, CANCELLED] }
      responses:
        '201':
          description: Created
  /orders/{id}:
    patch:
      summary: Update order status
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [status]
              properties:
                status: { type: string, enum: [NEW, PAID, CANCELLED] }
      responses:
        '200':
          description: OK
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
